baseURL = 'https://joseabuan.com/'
languageCode = 'en-us'
theme = 'PaperMod'

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10
[[menu.main]]
    identifier = "about me"
    name = "About Me"
    url = ""
    weight = 10

[params]
    defaultTheme = "dark" # Perfect for the CS aesthetic
    showCodeCopyButtons = true
    mainSections = ["posts", "hikes"]
[markup.goldmark.renderer]
    unsafe = true
[params.homeInfoParams]
    Title = "Jose Abuan"
    Content = """
<div class="home-hero">
  <div class="home-hero-text">
    Hello World! I'm Jose, I'm passionate at solving problems (and creating new ones). Nowadays, I enjoy looking
    at data and coming up with questions and solutions. When I'm not doing those, you can find me enjoying the outdoors
    or working in the gym.
  </div>
  <img src="/images/personal_portrait.jpeg" alt="Jose Abuan" class="home-hero-img">
</div>
<div style="margin-top: 16px;">
  <a href="/resume.pdf" target="_blank" rel="noopener" style=" text-decoration: underline;">
    My Experience
  </a>
</div>

"""

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/jose-abuan"
[[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/jose-abuan" 
[[params.socialIcons]]
    name = "youtube"
    url = "https://youtube.com/@mynamehosehimenez"    
[[params.socialIcons]]
    name = "discord"
    url = "https://discordapp.com/users/jose_63032"    
[[params.socialIcons]]
    name = "email"
    url = "mailto:abuanjosel@gmail.com"   
[[params.socialIcons]]
    name = "rss"
    url = "/index.xml"
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]